version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 6
    labels:
      - dependencies
      - npm
    groups:
      npm-production-minor-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
      npm-development-minor-patch:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 4
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch
