import type { Tool } from "@/lib/tools/types";

export const tools: Tool[] = [
  {
    id: "pourcentage",
    slug: "pourcentage",
    categoryId: "calculs",
    icon: "📊",
    name: "Calculateur de pourcentage",
    nameByLocale: { fr: "Calculateur de pourcentage", en: "Percentage Calculator" },
    description: "Calculez facilement un pourcentage, une évolution ou une différence.",
    descriptionByLocale: { fr: "Calculez facilement un pourcentage, une évolution ou une différence.", en: "Easily calculate a percentage, change, or difference." },
    keywords: ["%", "évolution", "différence", "variation", "taux"],
    keywordsByLocale: { fr: ["%","évolution","différence","variation","taux"], en: ["%","change","difference","variation","rate"] },
    available: true,
  },
  {
    id: "reduction",
    slug: "reduction",
    categoryId: "calculs",
    icon: "🏷️",
    name: "Calculateur de réduction",
    nameByLocale: { fr: "Calculateur de réduction", en: "Discount Calculator" },
    description: "Calculez le prix après une réduction et le montant économisé.",
    descriptionByLocale: { fr: "Calculez le prix après une réduction et le montant économisé.", en: "Calculate the price after a discount and the amount saved." },
    keywords: ["remise", "promotion", "solde", "prix", "économie"],
    keywordsByLocale: { fr: ["remise","promotion","solde","prix","économie"], en: ["discount","promotion","sale","price","savings"] },
    available: true,
  },
  {
    id: "tva",
    slug: "tva",
    categoryId: "calculs",
    icon: "💶",
    name: "Calculateur TVA HT / TTC",
    nameByLocale: { fr: "Calculateur TVA HT / TTC", en: "VAT Calculator" },
    description: "Convertissez facilement un prix HT en TTC et inversement.",
    descriptionByLocale: { fr: "Convertissez facilement un prix HT en TTC et inversement.", en: "Easily convert a price between excluding and including VAT." },
    keywords: ["taxe", "hors taxe", "toutes taxes", "prix", "tva", "ht", "ttc"],
    keywordsByLocale: { fr: ["taxe","hors taxe","toutes taxes","prix","tva","ht","ttc"], en: ["tax","excluding VAT","including VAT","price","vat"] },
    available: true,
  },
  {
    id: "regle-de-trois",
    slug: "regle-de-trois",
    categoryId: "calculs",
    icon: "⚖️",
    name: "Règle de trois",
    nameByLocale: { fr: "Règle de trois", en: "Rule of Three Calculator" },
    description: "Résolvez rapidement vos calculs de proportionnalité.",
    descriptionByLocale: { fr: "Résolvez rapidement vos calculs de proportionnalité.", en: "Quickly solve proportion and ratio calculations." },
    keywords: ["proportion", "proportionnalité", "ratio", "quantité", "prix"],
    keywordsByLocale: { fr: ["proportion","proportionnalité","ratio","quantité","prix"], en: ["proportion","ratio","quantity","price"] },
    available: true,
  },
  {
    id: "age",
    slug: "age",
    categoryId: "dates",
    icon: "🎂",
    name: "Calculateur d'âge",
    nameByLocale: { fr: "Calculateur d'âge", en: "Age Calculator" },
    description: "Calculez précisément votre âge à partir d'une date de naissance.",
    descriptionByLocale: { fr: "Calculez précisément votre âge à partir d'une date de naissance.", en: "Precisely calculate your age from a date of birth." },
    keywords: ["anniversaire", "naissance", "date"],
    keywordsByLocale: { fr: ["anniversaire","naissance","date"], en: ["birthday","birth","date"] },
    available: true,
  },
  {
    id: "duree",
    slug: "duree",
    categoryId: "dates",
    icon: "⏱️",
    name: "Calculateur de durée",
    nameByLocale: { fr: "Calculateur de durée", en: "Duration Calculator" },
    description: "Calculez la durée entre deux dates ou deux horaires.",
    descriptionByLocale: { fr: "Calculez la durée entre deux dates ou deux horaires.", en: "Calculate the duration between two dates or two times." },
    keywords: ["temps", "date", "heures", "jours", "intervalle"],
    keywordsByLocale: { fr: ["temps","date","heures","jours","intervalle"], en: ["time","date","hours","days","interval"] },
    available: true,
  },
  {
    id: "vitesse-telechargement",
    slug: "vitesse-telechargement",
    categoryId: "informatique",
    icon: "🚀",
    name: "Mbps ↔ Mo/s",
    nameByLocale: { fr: "Mbps ↔ Mo/s", en: "Mbps ↔ MB/s Converter" },
    description: "Convertissez une vitesse Internet entre Mbps et Mo/s.",
    descriptionByLocale: { fr: "Convertissez une vitesse Internet entre Mbps et Mo/s.", en: "Convert an Internet speed between Mbps and MB/s." },
    keywords: ["internet", "débit", "connexion", "megabit", "mégaoctet"],
    keywordsByLocale: { fr: ["internet","débit","connexion","megabit","mégaoctet"], en: ["internet","speed","connection","megabit","megabyte"] },
    available: true,
  },
  {
    id: "temps-telechargement",
    slug: "temps-telechargement",
    categoryId: "informatique",
    icon: "⏳",
    name: "Temps de téléchargement",
    nameByLocale: { fr: "Temps de téléchargement", en: "Download Time Calculator" },
    description: "Estimez le temps nécessaire pour télécharger un fichier.",
    descriptionByLocale: { fr: "Estimez le temps nécessaire pour télécharger un fichier.", en: "Estimate the time needed to download a file." },
    keywords: ["download", "internet", "débit", "fichier", "durée"],
    keywordsByLocale: { fr: ["download","internet","débit","fichier","durée"], en: ["download","internet","speed","file","duration"] },
    available: true,
  },
  {
    id: "taille-fichier",
    slug: "taille-fichier",
    categoryId: "informatique",
    icon: "💾",
    name: "Calculateur de taille de fichier",
    nameByLocale: { fr: "Calculateur de taille de fichier", en: "File Size Calculator" },
    description: "Estimez la taille d'un fichier selon sa durée et son débit.",
    descriptionByLocale: { fr: "Estimez la taille d'un fichier selon sa durée et son débit.", en: "Estimate a file size from its duration and bitrate." },
    keywords: ["poids", "taille", "stockage", "vidéo", "audio"],
    keywordsByLocale: { fr: ["poids","taille","stockage","vidéo","audio"], en: ["size","storage","video","audio","bitrate"] },
    available: false,
  },
  {
    id: "convertisseur-taille",
    slug: "convertisseur-taille",
    categoryId: "informatique",
    icon: "🔄",
    name: "Convertisseur de taille",
    nameByLocale: { fr: "Convertisseur de taille", en: "File Size Converter" },
    description: "Convertissez facilement Ko, Mo, Go, To et autres unités.",
    descriptionByLocale: { fr: "Convertissez facilement Ko, Mo, Go, To et autres unités.", en: "Easily convert KB, MB, GB, TB and other units." },
    keywords: ["ko", "mo", "go", "to", "octets", "stockage"],
    keywordsByLocale: { fr: ["ko","mo","go","to","octets","stockage"], en: ["kb","mb","gb","tb","bytes","storage"] },
    available: true,
  },
  {
    id: "mots-caracteres",
    slug: "mots-caracteres",
    categoryId: "fichiers",
    icon: "🔤",
    name: "Compteur de mots et caractères",
    nameByLocale: { fr: "Compteur de mots et caractères", en: "Word and Character Counter" },
    description: "Comptez les mots, caractères, espaces et lignes d'un texte.",
    descriptionByLocale: { fr: "Comptez les mots, caractères, espaces et lignes d'un texte.", en: "Count words, characters, spaces, and lines in a text." },
    keywords: ["texte", "lettres", "compter", "ligne", "paragraphes"],
    keywordsByLocale: { fr: ["texte","lettres","compter","ligne","paragraphes"], en: ["text","letters","count","line","paragraphs"] },
    available: false,
  },
  {
    id: "bitrate-video",
    slug: "bitrate-video",
    categoryId: "video",
    icon: "🎬",
    name: "Calculateur bitrate vidéo",
    nameByLocale: { fr: "Calculateur bitrate vidéo", en: "Video Bitrate Calculator" },
    description: "Calculez le bitrate ou la taille approximative d'une vidéo.",
    descriptionByLocale: { fr: "Calculez le bitrate ou la taille approximative d'une vidéo.", en: "Calculate the bitrate or approximate size of a video." },
    keywords: ["vidéo", "qualité", "débit", "encodage", "compression"],
    keywordsByLocale: { fr: ["vidéo","qualité","débit","encodage","compression"], en: ["video","quality","bitrate","encoding","compression"] },
    available: false,
  },
];
