import type { Tool } from "@/lib/tools/types";
import { validateToolCatalog } from "@/lib/tools/metadata";

export const tools: Tool[] = [
  {
    id: "pourcentage",
    slug: "pourcentage",
    categoryId: "calculs",
    icon: "📊",
    name: "Calculateur de pourcentage",
    description: "Calculez facilement un pourcentage, une évolution ou une différence.",
    keywords: ["%", "évolution", "différence", "variation", "taux"],
    available: true,
  },
  {
    id: "reduction",
    slug: "reduction",
    categoryId: "calculs",
    icon: "🏷️",
    name: "Calculateur de réduction",
    description: "Calculez le prix après une réduction et le montant économisé.",
    keywords: ["remise", "promotion", "solde", "prix", "économie"],
    available: true,
  },
  {
    id: "tva",
    slug: "tva",
    categoryId: "calculs",
    icon: "💶",
    name: "Calculateur TVA HT / TTC",
    description: "Convertissez facilement un prix HT en TTC et inversement.",
    keywords: ["taxe", "hors taxe", "toutes taxes", "prix", "tva", "ht", "ttc"],
    available: true,
  },
  {
    id: "regle-de-trois",
    slug: "regle-de-trois",
    categoryId: "calculs",
    icon: "⚖️",
    name: "Règle de trois",
    description: "Résolvez rapidement vos calculs de proportionnalité.",
    keywords: ["proportion", "proportionnalité", "ratio", "quantité", "prix"],
    available: true,
  },
  {
    id: "age",
    slug: "age",
    categoryId: "dates",
    icon: "🎂",
    name: "Calculateur d'âge",
    description: "Calculez précisément votre âge à partir d'une date de naissance.",
    keywords: ["anniversaire", "naissance", "date"],
    available: true,
  },
  {
    id: "duree",
    slug: "duree",
    categoryId: "dates",
    icon: "⏱️",
    name: "Calculateur de durée",
    description: "Calculez la durée entre deux dates ou deux horaires.",
    keywords: ["temps", "date", "heures", "jours", "intervalle"],
    available: true,
  },
  {
    id: "vitesse-telechargement",
    slug: "vitesse-telechargement",
    categoryId: "informatique",
    icon: "🚀",
    name: "Mbps ↔ Mo/s",
    description: "Convertissez une vitesse Internet entre Mbps et Mo/s.",
    keywords: ["internet", "débit", "connexion", "megabit", "mégaoctet"],
    available: true,
  },
  {
    id: "temps-telechargement",
    slug: "temps-telechargement",
    categoryId: "informatique",
    icon: "⏳",
    name: "Temps de téléchargement",
    description: "Estimez le temps nécessaire pour télécharger un fichier.",
    keywords: ["download", "internet", "débit", "fichier", "durée"],
    available: true,
  },
  {
    id: "taille-fichier",
    slug: "taille-fichier",
    categoryId: "informatique",
    icon: "💾",
    name: "Calculateur de taille de fichier",
    description: "Estimez la taille d'un fichier selon sa durée et son débit.",
    keywords: ["poids", "taille", "stockage", "vidéo", "audio"],
    available: false,
  },
  {
    id: "convertisseur-taille",
    slug: "convertisseur-taille",
    categoryId: "informatique",
    icon: "🔄",
    name: "Convertisseur de taille",
    description: "Convertissez facilement Ko, Mo, Go, To et autres unités.",
    keywords: ["ko", "mo", "go", "to", "octets", "stockage"],
    available: true,
  },
  {
    id: "mots-caracteres",
    slug: "mots-caracteres",
    categoryId: "fichiers",
    icon: "🔤",
    name: "Compteur de mots et caractères",
    description: "Comptez les mots, caractères, espaces et lignes d'un texte.",
    keywords: ["texte", "lettres", "compter", "ligne", "paragraphes"],
    available: false,
  },
  {
    id: "bitrate-video",
    slug: "bitrate-video",
    categoryId: "video",
    icon: "🎬",
    name: "Calculateur bitrate vidéo",
    description: "Calculez le bitrate ou la taille approximative d'une vidéo.",
    keywords: ["vidéo", "qualité", "débit", "encodage", "compression"],
    available: false,
  },
].map((tool): Tool => ({
  ...tool,
  version: 1,
  complexity: "small",
  categories: [tool.categoryId],
  content: { fr: { name: tool.name, description: tool.description } },
  tags: tool.keywords ?? [],
  aliases: tool.keywords ?? [],
  seo: {
    title: tool.name + " | Utiluna",
    description: tool.description,
  },
  examples: [],
  processing: {
    mode: "local",
    dataCategories: [],
    externalProviders: [],
    storage: "none",
    retention: "Aucune donnée n'est transmise ou stockée par Utiluna.",
    fallback: "Le traitement ne dépend pas d'un service distant.",
  },
  capabilities: ["local-processing"],
  browserRequirements: { apis: [] },
  offline: true,
  sharing: { supported: false, mode: "none" },
  relatedToolIds: [],
  quality: {
    accessibility: "required",
    performance: "standard",
    tests: "required",
  },
  lifecycle: tool.available ? "published" : "draft",
  contributor: { type: "internal" },
}));

validateToolCatalog(tools);
